### ISSUE TITLE
Error in exporting TAG 2 Moves

### ISSUE THREAD

**Issue by FPISSUM** [Kiloutre/TekkenMovesetExtractor#11]
I was following I AM OP's guide for using your extractor (https://www.youtube.com/watch?v=qF2UEWWShTs&t=0s) and for the most part there were no issues with exporting/importing Tekken 7 movesets (https://twitter.com/FPISSUM/status/1265664258697596928?s=20). When it came to Tag 2 I did pretty much what I AM OP asks in the guide. I downloaded the latest version of Cemu (1.19.1b), downloaded a TAG2 Iso v16 (US), booted the game up, copied the base address from the CEMU Log, and pasted it into the game addresses.txt of the Extractor. Once I clicked on "Export: Tekken Tag2: Player 1" this error would pop up

Exception in Tkinter callback
Traceback (most recent call last) :
   File "tkinter\_init_.py", line 1702, in _call_
   File "GUI_TekkenMovesetExtractor.py", line 609, in
"lambda"
   File "GUI_TekkenMovesetExtractor.py", line 320, in
exportTag2Character
   File "morbinExport.py", line 62, in _init_
   File "Addresses.py", line 49, in _init_
pywintypes.error" (5, 'OpenProcess', 'Access is denied.')

(<> = text, lambda, inside won't appear preview so replaced with "" and attached screenshot of error)

This doesn't seem to be an error most encounter with when I asked. I tried some other things such as upgrading and downgrading the Tag 2 version (USv16 --> USv32 | USv32 --> USv16 ), and using older versions of the Extractor but they didn't work out and the same error pops up.

Attached are the screenshots of the after mentioned error, Tag 2 Cemu Screen, Cemu Log, & TNE Game Addresses Log.

![TNE Error](https://user-images.githubusercontent.com/66355535/83610804-9b827000-a5b2-11ea-931b-5aa00a01f689.png)
![Tag 2 Screen](https://user-images.githubusercontent.com/66355535/83610873-b94fd500-a5b2-11ea-96c0-eac916434580.png)
![CEMU Log](https://user-images.githubusercontent.com/66355535/83610883-bead1f80-a5b2-11ea-9d19-374a7617b016.png)
![TNE Game Addresses Log](https://user-images.githubusercontent.com/66355535/83610890-c076e300-a5b2-11ea-8449-78690b5ea2ae.png)

**Comment by nikpikjoe** [comment]
Make sure you've started the moveset extractor as admin. Also, the base address changes every time you relaunch CEMU - make sure that CEMU is running while you take the latest base address from the log. 

Aside from that - it's probably an issue with your pirated ISO; a lot of Tag 2 ISOs floating around the internet have their regions mislabelled (which CEMU doesn't care about, but the moveset extractor does). Try switching the p1_addr values around and seeing if that helps, otherwise dump the game yourself or find a more legit ISO basically.

**Comment by FPISSUM** [comment]
> Make sure you've started the moveset extractor as admin. Also, the base address changes every time you relaunch CEMU - make sure that CEMU is running while you take the latest base address from the log.

I've always changed the CEMU address upon every boot up & keep the application on whilst extracting the moves (Pretty much as the guide states). However, I haven't tried running the Extractor as an Admin, I'll get to this thread after trying that method out plus the others.

> Aside from that - it's probably an issue with your pirated ISO; a lot of Tag 2 ISOs floating around the internet have their regions mislabelled (which CEMU doesn't care about, but the moveset extractor does). Try switching the p1_addr values around and seeing if that helps, otherwise dump the game yourself or find a more legit ISO basically.

I see, I didn't really suspect pirated copies around the net or any copy on the net for that matter to have mislabelled regions. I attempted to switch p1_addr values previously and that didn't work our as well. I tried using cheat engine to find the P1 value but since I don't really understand how to use it with the help of informative guides I dropped that all together.

**Comment by Leeges94** [comment]
I can link the Move Extractor latest version with all of the characters for people having issues extracting without the need for TTT2 iso just let me no

**Comment by FPISSUM** [comment]
> Make sure you've started the moveset extractor as admin. Also, the base address changes every time you relaunch CEMU - make sure that CEMU is running while you take the latest base address from the log.

Running the Extractor as Admin made it worked like a charm. I'm not sure if that is because I've set CEMU to be ran as an Admin before while the Extractor wasn't hence the 'Access is denied' error appeared. Both apps are now set to run as admin and it works perfectly.

Much thanks!
