### ISSUE TITLE
How to use "Go to current move ID" button in the editor?

### ISSUE THREAD

**Issue by Crispy13** [Kiloutre/TekkenMovesetExtractor#13]
What's the purpose of it?

**Comment by Kiloutre** [comment]
If the moveset you're editing is the same as the one the player is using, the button allows you to go to the current move instead of having to find the current move ID and name on your own. Finding a single move within the list of 2000+ moves each character have would be hard without that

**Comment by Crispy13** [comment]
Thank you for your reply.
So if i click the button after i use a move(e.g. lprp) in game, will lprp move be selected in the editor?

**Comment by Crispy13** [comment]
Use a move and pause the game then click the button.
