### ISSUE TITLE
Figuring out move and string executions and timings

### ISSUE THREAD

**Issue by compsyguy** [Kiloutre/TekkenMovesetExtractor#14]
First off, thank you for creating this tool. I've been wanting to make something to extract the movelist info, but was never able to get it figured out.

I was wondering though, if this could be used to figure out how to extract the inputs and timings on how to execute moves?
I see that you've figured out how to get the cancel data - it looks to me like that's how you determine what moves can be done after specific moves.

In the editor window, I see you've got the 'Cancel list' which seems like it would show the moves the currently selected move can cancel into, but it doesn't seem to be updating when I select a new move. How does the Cancel list interact with the selected move?
Thank you

**Comment by Kiloutre** [comment]
You need to click the blue "cancel_idx" text in the move data to load its cancels. You got it right bout cancels being the only way for one move to transition into another.
