### ISSUE TITLE
Way to access & modify Grouped_cancels section?

### ISSUE THREAD

**Issue by kse181** [Kiloutre/TekkenMovesetExtractor#15]
I realized that grouped_cancels part have an important role to making new moves on unused commands. but It seems impossible to access right grouped_cancel id, unlike normal Cancel id.

**Comment by Kiloutre** [comment]
This has now been added in the latest release. Group cancels can be accessed by clicking move_id if the current cancel is referencing a group_cancel (you can tell it does if its command is equal to 0x800b)
