### ISSUE TITLE
how to use this tool in online mode please?

### ISSUE THREAD

**Issue by jrksaucy** [Kiloutre/TekkenMovesetExtractor#18]
dear boss,my english is poor , so i hope you can read it

the problem is, if can not both online player use this tool, how to use this tool in online mode?

like this:
https://www.bilibili.com/video/BV1fK411W7A1

It always sync failure then I try to import or set online local player, please teach me how to use moveset online

**Comment by Kiloutre** [comment]
Both player must run the program. You must put the character you want to play into "Set Online Local Player", and the character your opponent is going to play into "Set Online Remote Player".
The opponent must do the same on his end, put his own character into "Local player" and your charcter into "remote player"

**Comment by jrksaucy** [comment]
so this tool can not using with stranger online opponent?

**Comment by jrksaucy** [comment]
https://www.youtube.com/watch?v=CTiEi

**Comment by Kiloutre** [comment]
No, it cannot be used against strangers
