### ISSUE TITLE
Question about Input direction and requirements

### ISSUE THREAD

**Issue by compsyguy** [Kiloutre/TekkenMovesetExtractor#20]
It looks like the input direction in the cancel from GUI_TekkenMovesetEditor.getCommandStr is a bitmask?
I'm wondering since I'm trying to figure out a few of the input  directions that come up as unknown.

For example Nina's 1,2~U_D transitions to a side step, the direction bits variable has the value of 896, but I'm not sure how the function figures out the direction, since I'm not familiar enough with the bitwise opperators. It looks like it just looks for one specific direction?

I was also wondering if there was any documentation on what the 'requirements' in the cancels were.

Thank you

**Comment by Kiloutre** [comment]
Yeah, a cancel's command is generally (not always) stored using bits. It's split into two groups of 32 bits each: one group for the joystick direction, and the other for the actual buttons (1, 2, 3, 4, and more). This part is not particularly complicated, however the command can also store a reference to bufferable input sequences (Jet Upper, QCF motions, dash/backdash motion, etc). And to top it off, there are more than just 1 2 3 4 or Up/Down/Left/right in the button side and direction side, and i don't know what these are for yet.

Requirements for the most part are just conditions that determine whether a specific cancel can trigger or not, or whether an attack will result in a specific reaction or another (CH moves use that a lot). They can sometimes do more, but i haven't quite documented that yet.
