### ISSUE TITLE
How exactly does the moveset editor work?

### ISSUE THREAD

**Issue by QwikQikJr** [Kiloutre/TekkenMovesetExtractor#21]
I don't understand how to find what moves that I'm looking for, and there are a lot of things in the UI that I don't understand. For example, I have no clue what things like "hitcondition_itx" mean.

**Comment by Kiloutre** [comment]
Not much i can help with here, i don't fully understand moveset either. Best way to learn is to change stuff and see what effects it has in-game. You'll learn more stuff than i know pretty quickly by doing that.
