### ISSUE TITLE
Some buttons are deactivated. (1.0.12)

### ISSUE THREAD

**Issue by Crispy13** [Kiloutre/TekkenMovesetExtractor#23]
![image](https://user-images.githubusercontent.com/47196430/85194365-76a73000-b308-11ea-840e-60a60c5595b6.png)
![image](https://user-images.githubusercontent.com/47196430/85194430-8e7eb400-b308-11ea-8fe7-bc0b28ef67a7.png)

Is it normal or did i mess up?

**Comment by Kiloutre** [comment]
Those features haven't been made yet, they will come in future releases

**Comment by Crispy13** [comment]
Thank you for replying. By the way, I'm glad that i can use this tool.
