### ISSUE TITLE
No extracted movesets visible in the editor (1.0.16)

### ISSUE THREAD

**Issue by JustBlaze96** [Kiloutre/TekkenMovesetExtractor#27]
In the latest update, after trying to open the moveset editor, none of my previously exported movesets were available. On the main window those lines of text appeared
![Beta 1 0 16](https://user-images.githubusercontent.com/63187573/86083209-e2706200-ba99-11ea-8787-278a6e8fcca8.png)

Overall experiences with the program are great! I can't wait for further updates!

**Comment by Kiloutre** [comment]
Ah, i think it has to do with the lack of _ in your moveset names, it's a stupid bug. Try to respect the usual folder name format (t7_JIN, tag2_LAW) and it should fix it for now

**Comment by JustBlaze96** [comment]
It sure did work! Thank you so much!
I can't wait till the requirement id bits for Rage get discovered! The more I work in the program, the more I understand it. I try to discover stuff myself but I'm not too good at this LOL
