### ISSUE TITLE
Using T5 Moveset in T7 causes the character to just roll forward

### ISSUE THREAD

**Issue by Lucasius2000** [Kiloutre/TekkenMovesetExtractor#29]
Extracting from PCSX2 was no problem, but when I tried to use the movesets in T7, my character just starts to roll forward. I was trying to extract Jinpachi and Nina.

**Comment by Kiloutre** [comment]
T5 is not properly supported yet so this is inevitable and will be for a while

**Comment by Lucasius2000** [comment]
Ok, thanks for the info! Looking forward for future updates!
