### ISSUE TITLE
Latest version wang df3+4 and waning moon no longer working

### ISSUE THREAD

**Issue by Luke-MacInnes1803698** [Kiloutre/TekkenMovesetExtractor#3]

**Comment by Kiloutre** [comment]
Fixing sidesteps broke other moves but it's inevitable, there was no way of fixing sidestep otherwise. Random moves from every character got broken in the process, but fixing it does not take long, so keep reporting if you find broken moves from other characters

**Comment by Luke-MacInnes1803698** [comment]
Will do been having a lot of fun with this so far so I'll keep you updated if I find anything else

**Comment by Kiloutre** [comment]
Fixed
