### ISSUE TITLE
moveset import crash

### ISSUE THREAD

**Issue by Rafiizas** [Kiloutre/TekkenMovesetExtractor#32]
Game crashes if you import movesets to P1 and P2 and then juggle the opponent. This doesn't happen on v1.0.24. The game crashes when both movesets were exported on 1.0.26.

Here's an example:
https://www.youtube.com/watch?v=13DuJBiAHdc

Is there something on my end?

**Comment by Kiloutre** [comment]
Thanks a lot for the bug report! I just made a new release that fixes that bug.
