### ISSUE TITLE
Is a bug or glitch? (1.0.24)

### ISSUE THREAD

**Issue by RunStepStrike** [Kiloutre/TekkenMovesetExtractor#33]
Before editing movesets, every my cancel last must normal move_ids.

But, since yesterday, every cancels(no exceptions for added and defaults)' last moveids are broken.(every 5digit moveid aliases are broken. Like [value]-1)

Any reasons..?
![bug.png](https://user-images.githubusercontent.com/68704500/90603262-fdf41f80-e235-11ea-8eb5-e28877cd7d26.png)

**Comment by Kiloutre** [comment]
What do you mean broken? Do you get any errors?

**Comment by RunStepStrike** [comment]
> What do you mean broken? Do you get any errors?

BG moveset editing window is  older moveset from 1.0.24(aka r3),
Fore editing window is current moveset (aka r4).

r3 is currently work fine.

r4 is "strictly" work fine. But, every cancels' last list(must be [AUTO].)s' move ids are broken

example) in cancel list 0, must be ##_sKAM(32769)
But, in bugged or glitched anyway, be ##_Direct (32768)

Every moveid s numeric values are being origin value - 1.

Although I edited my movesets and cancels, i didn't edit such as essential cancels like 'cancel list 0'.

**Comment by RunStepStrike** [comment]
> What do you mean broken? Do you get any errors?

If I apply moveset which cancels are broken, character goes freeze.Can't control, can't guard or move, except hit by enemies for few frames.

**Comment by Kiloutre** [comment]
It's fixed?
