### ISSUE TITLE
Is there any ways to export T7 S1 or S2?

### ISSUE THREAD

**Issue by RunStepStrike** [Kiloutre/TekkenMovesetExtractor#35]
I have Tekken 7 Season 1 and Season 2 Stand-alone executables. But can't export using Extractor.

How to use that thing in older Tekken 7? I have a latest Cheat Engine

**Comment by Kiloutre** [comment]
It would require finding the p1 address and the player struct size. The readme on the main page should give some instructions as to how to do it.
