### ISSUE TITLE
Armor King's running 2+4 throw not working

### ISSUE THREAD

**Issue by kse181** [Kiloutre/TekkenMovesetExtractor#4]
also ss 1 , 2 not work

**Comment by Kiloutre** [comment]
This should have been fixed in the last release, i assume that's why you closed it

**Comment by kse181** [comment]
still not working on v0.9.2

**Comment by Luke-MacInnes1803698** [comment]
I was able to do aks shining wizard, it did feel much tighter than it should be though

**Comment by kse181** [comment]
![Honeycam 2020-05-28 22-49-42](https://user-images.githubusercontent.com/66022423/83149451-0d7f3300-a135-11ea-83ec-2e337177d441.gif)
even bot can't do

**Comment by Luke-MacInnes1803698** [comment]
one sec i'll try it again

**Comment by Kiloutre** [comment]
You're right it's broken, i just made a release to fix it
