### ISSUE TITLE
1.0.32.14 moveset editor error

### ISSUE THREAD

**Issue by RunStepStrike** [Kiloutre/TekkenMovesetExtractor#46]
![extractor error](https://user-images.githubusercontent.com/68704500/120077047-67695e80-c0e3-11eb-8b45-3aebf2ab9efd.png)

When using 1.0.32.14, Can't load when using moveset Editor.

While that movesets were edited in 1.0.32.9, can import to 4.20 patch version.

Kinda glitch happened.

**Comment by Kiloutre** [comment]
Thank you for your report, this has been fixed in the latest version
