### ISSUE TITLE
Unknown Bug

### ISSUE THREAD

**Issue by TownofRainfall** [Kiloutre/TekkenMovesetExtractor#63]
I have been trying to use the moveset extractor for Tekken 7 but experience the following error whenever I attempt to export or import movesets: 
![error code](https://user-images.githubusercontent.com/95550396/144726824-8afe4119-d705-404b-a094-514f6e111792.JPG)

As far as I know, I have the latest version of TekkenMovesetExtractor, and I run it as admin every time I use it. I experience the same error with any moveset or character I try it with. Other functions such as the camera animator don't seem to work as well. 

Thanks for the assistance.

**Comment by Kiloutre** [comment]
I'm seeing you are running an old version of the tool (1.0.32.20), check the releases page (https://github.com/Kiloutre/TekkenMovesetExtractor/releases) for more recent versions, the one you are running is too old for the current Tekken patch. Tekken updates frequently break the tool, although i am working on getting around that.
