### ISSUE TITLE
Is it possible to make the imported moveset staying constantly during offline play?

### ISSUE THREAD

**Issue by zhuwz1** [Kiloutre/TekkenMovesetExtractor#86]
For example, I want to play as Boss Devil Kazuya all through arcade mode. Now after each loading screen, I have to switch back to desktop and click to Import button. So in future can you add a function to lock the imported moveset during offline play? Thanks.

**Comment by Kiloutre** [comment]
The "Set Online Local Player" can accomplish that purpose even if i recognize they're poorly named
